### ISSUE TITLE
The code is not structured properly

### ISSUE THREAD

**Issue by Sooraj002** [Rakesh9100/Beautiify#754]
The Whole code is not structured properly which reduces code readability.

**Comment by Sooraj002** [comment]
I would like to fix this issue and i have already fixed it and it is not breaking any thing and works completely.
I am a gssoc contributor.
Please assign me this issue

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.
